server:
  port: 8090

spring:
  profiles:
    active: test

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

crud:
  create: java:jms/queue/music/create
  create-answer: java:jms/queue/music/create-answer
  read: java:jms/queue/music/askedBy
  read-answer: java:jms/queue/music/askedBy-answer
  update: java:jms/queue/music/update
  update-answer: java:jms/queue/music/update-answer
  delete: java:jms/queue/music/delete
  delete-answer: java:jms/queue/music/delete-answer
  authentication: java:jms/queue/music/auth
  authentication-answer: java:jms/queue/music/auth-answer
  read-user-by-login: java:jms/queue/user/find-by-login
  read-user-by-login-answer: java:jms/queue/user/find-by-login-answer
  create-user: java:jms/queue/user/create


